@echo off 
< "%~f0" more +4 > t.vbs 
cscript //nologo t.vbs & del t.vbs 
goto :eof 
set ierunner = CreateObject("wscript.shell") 
REM Ð»Íþ
ierunner.run "cmd /c start iexplore http://172.16.15.228/dinner/index.asp",0 
wscript.sleep 3000

ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100

ierunner.sendkeys "username1" 
ierunner.sendkeys "{TAB}"
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
ierunner.sendkeys "password1"
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{ENTER}"

wscript.sleep 3000
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{ENTER}"

wscript.sleep 1000
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{ENTER}"

wscript.sleep 500
ierunner.sendkeys "{ENTER}"
wscript.sleep 200
ierunner.sendkeys "%"
ierunner.sendkeys "{UP}"
ierunner.sendkeys "{UP}"
ierunner.sendkeys "{ENTER}"

REM ºúÏþÅô
ierunner.run "cmd /c start iexplore http://172.16.15.228/dinner/index.asp",0 
wscript.sleep 3000

ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100

ierunner.sendkeys "username2" 
ierunner.sendkeys "{TAB}"
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
ierunner.sendkeys "password2"
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{ENTER}"

wscript.sleep 3000
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{ENTER}"

wscript.sleep 1000
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{TAB}" 
wscript.sleep 100
ierunner.sendkeys "{ENTER}"

wscript.sleep 500
ierunner.sendkeys "{ENTER}"
wscript.sleep 200
ierunner.sendkeys "%"
ierunner.sendkeys "{UP}"
ierunner.sendkeys "{UP}"
ierunner.sendkeys "{ENTER}"